---

- name: GA | Cert LetsEncrypt | Checking if key
  stat:
    path: "{{ ga_letsencrypt_live_dir }}/privkey.pem"
  register: domain_key

- name: GA | Cert LetsEncrypt | Creating key/cert directories
  file:
    path: "{{ item }}"
    state: directory
    owner: 'root'
    group: 'root'
    mode: 0755
  with_items:
  - '/etc/ssl/private'
  - '/etc/ssl/certs'

- name: GA | Cert LetsEncrypt | Initializing certbot
  include_tasks: domain_new.yml
  when: not domain_key.stat.exists

- name: GA | Cert LetsEncrypt | Linking certificates
  file:
    state: link
    src: "{{ item.key }}"
    dest: "{{ item.value }}"
  with_dict:
    - {"{{ ga_letsencrypt_live_dir }}/privkey.pem": "{{ ga_ssl_path_key }}"}
    - {"{{ ga_letsencrypt_live_dir }}/cert.pem": "{{ ga_ssl_path_cert }}"}
    - {"{{ ga_letsencrypt_live_dir }}/fullchain.pem": "{{ ga_ssl_path_fullchain }}"}
