---

- name: GA | LetsEncrypt | Creating alternative name string (1/3)
  set_fact:
    _alias: "{{ apache_alias | join(' --domain ') }}"
  when:
    - apache_alias | length > 0

- name: GA | LetsEncrypt | Creating alternative name string (2/3)
  set_fact:
    _apache_alias: "{{ '--domain ' + _alias }}"
  when:
    - apache_alias | length > 0

- name: GA | LetsEncrypt | Creating alternative name string (3/3)
  set_fact:
    _apache_alias: ''
  when:
    - apache_alias | length == 0

- name: GA | LetsEncrypt | Debug => the following command will be issued
  ansible.builtin.debug:
    msg: "certbot certonly --apache -{{ certbot_verbosity }} --non-interactive --agree-tos --email {{ certbot_email }} --cert-name {{ ga_web_key }}
             --rsa-key-size {{ letsencrypt_key_size }} --no-redirect --domain {{ ga_web_dns }} {{ _apache_alias }} --cert-path {{ _path_cert }}"

- name: GA | LetsEncrypt | Certbot | Starting certbot
  shell: "certbot certonly --apache -{{ certbot_verbosity }} --non-interactive --agree-tos --email {{ certbot_email }} --cert-name {{ ga_web_key }}
           --rsa-key-size {{ letsencrypt_key_size }} --no-redirect --domain {{ ga_web_dns }} {{ _apache_alias }}"
  ignore_errors: yes
  notify: 'reload_apache'
