---

- name: GA | Web | Install packages
  apt:
    name: ['python3-pip', 'libapache2-mod-wsgi-py3']
    state: present
  notify: 'reload_apache'

- name: GA | Web | Django | Install python virtualenv
  pip:
    name: 'virtualenv'
    executable: pip3
    state: present
  notify: 'reload_apache'

- name: GA | Web | Django | Install python modules into venv
  pip:
    name: "{{ ga_django_mods }}"
    virtualenv: "{{ ga_web_path_venv }}"
    virtualenv_python: "{{ ga_python_version }}"
    state: present
  notify: 'reload_apache'
