---

- name: GA | Web | Django | Install python virtualenv
  pip:
    name: 'virtualenv'
    executable: pip3
    state: present

- name: GA | Web | Django | Install python modules into venv
  pip:
    name: "{{ ga_django_mods }}"
    virtualenv: "{{ ga_web_path_venv }}"
    virtualenv_python: "{{ ga_python_version }}"
    state: present
  notify: 'restart_apache'

- name: GA | Web | Django | Adding database config and update script
  template:
    src: "templates/var/www/ga/{{ item }}.j2"
    dest: "{{ ga_web_path }}/{{ item }}"
    owner: "{{ ga_web_service_user }}"
    group: "{{ ga_service_group }}"
    mode: 0440
  notify: 'restart_apache'
  with_items:
    - 'database.cnf'
    - 'update_schema.sh'

- name: GA | Web | Django | Configuring django settings
  lineinfile:
    path: "{{ ga_web_path }}/base/settings.py"
    regexp: '{{ item.search }}'
    line: '{{ item.replace }}'
  with_items: "{{ ga_django_setting_replacement }}"

- name: GA | Web | Django | Adding privileges
  template:
    src: 'templates/etc/sudoers.d/gaweb.j2'
    dest: '/etc/sudoers.d/gaweb'
    owner: 'root'
    group: 'root'
    mode: 0440
    validate: "/usr/sbin/visudo -cf %s"
