---

- name: GA | Web | Installing packages
  apt:
    name: ['apache2', 'python-setuptools', 'python3-pip', 'libapache2-mod-wsgi-py3']
    state: present
  notify: 'enable_apache'

- name: GA | Web | Add custom config options
  blockinfile:
    path: '/etc/apache2/apache2.conf'
    block: |
      {% for setting, value in ga_apache_config_additions.items() %}
        {{ setting }} {{ value }}
      {% endfor %}
    marker: "# {mark} ANSIBLE MANAGED BLOCK - custom config"
    validate: 'apachectl -t -f %s'
  notify: 'restart_apache'

- name: GA | Web | Adding service group
  group:
    name: "{{ ga_service_group }}"
    state: present

- name: GA | Web | Adding service user
  user:
    name: "{{ ga_web_service_user }}"
    shell: '/usr/sbin/nologin'
    home: "/home/{{ ga_web_service_user }}"
    groups: "{{ ga_web_groups }}"
    append: yes

- name: GA | Web | Creating directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ga_web_service_user }}"
    group: "{{ ga_service_group }}"
    mode: 0755
  with_items:
    - "{{ ga_web_path }}"
    - "{{ ga_web_path_log }}"
    - "{{ ga_web_path_static }}"
    - "{{ ga_web_path_venv }}"

- name: GA | Web | Checking if repo was already cloned
  stat:
    path: "{{ setup_clone_dir }}"
  register: tmp_clone_dir

- name: GA | Web | Cloning ga code
  git:
    repo: 'https://github.com/superstes/growautomation.git'
    dest: "{{ setup_clone_dir }}"
    depth: 1
  when: not tmp_clone_dir.stat.exists
#    version: "{{ ga_version }}"

- name: GA | Core | Copying web-code
  shell: "cp -r {{ setup_clone_dir }}/code/web {{ ga_web_path }} &&
  chown -R {{ ga_web_service_user }}:{{ ga_service_group }} {{ ga_web_path }} &&
  chmod 755 -R {{ ga_web_path }}"

- name: GA | Web | Enabling apache mods
  apache2_module:
    state: present
    name: "{{ item }}"
  with_items:
    - 'wsgi'
    - 'ssl'
    - 'rewrite'
  notify: 'reload_apache'
  ignore_errors: true

- name: GA | Web | Disabling autoindex
  apache2_module:
    state: absent
    name: 'autoindex'
    force: yes
  when: not ga_web_autoindex

- name: GA | Web | Disabling default apache sites
  file:
    state: absent
    dest: "/etc/apache2/sites-enabled/{{ item }}"
  with_items:
    - '000-default.conf'
    - 'default-ssl.conf'
  when: ga_web_disable_apache_default_sites
  notify: 'reload_apache'

- name: GA | Web | Configure apache site
  template:
    src: 'templates/etc/apache2/sites-available/ga.conf.j2'
    dest: '/etc/apache2/sites-available/ga.conf'
    owner: 'root'
    group: 'root'
    mode: 0644
  notify: 'reload_apache'

- name: GA | Web | Enable apache site
  file:
    state: link
    src: '/etc/apache2/sites-available/ga.conf'
    dest: '/etc/apache2/sites-enabled/ga.conf'
    owner: 'root'
    group: 'root'
    mode: 0644
  notify: 'reload_apache'

- name: GA | Configure UFW
  import_role:
    name: ufw
  when: ga_ufw_manage
