---

easyrsa:
  ca:
    default:
      certs:
        srv:
          - cn: "{{ ga_web_ssl_selfsigned_cn }}"
            sub_alt: "DNS:{{ ga_web_dns }}{% for alias in ga_web_alias %},DNS:{{ alias }}{% endfor %}"
            nopass: true

easyrsa_perms_pub: 644
easyrsa_perms_priv: 640

easyrsa_path: '/var/lib/easyrsa'
easyrsa_path_pki: "{{ easyrsa_path }}/pki"
easyrsa_cert_owner: "{{ ga_web_service_user }}"
easyrsa_cert_group: "{{ ga_service_group }}"

easyrsa_req_country: 'AT'
easyrsa_req_province: 'Styria'
easyrsa_req_city: 'GrowPlace'
easyrsa_req_org: 'GrowAutomation'
easyrsa_req_email: 'contact@growautomation.eu'
easyrsa_req_ou: 'IT'

easyrsa_key_size: '4096'
easyrsa_key_algo: 'rsa'
easyrsa_key_digest: 'sha512'
easyrsa_ca_runtime_days: '9125'
easyrsa_cert_runtime_days: '3650'
easyrsa_crl_days: '180'
easyrsa_renew_days: '90'

easyrsa_ca_cn: 'GrowAutomation SelfSign-CA'

key_generate_random_pwd: 'WILL_BE_RANDOM'
key_generate_random_pwd_ca: 'ca'
key_generate_random_pwd_cert: 'cert'
easyrsa_pwd_file: ".pwd_file"
easyrsa_ca_pwd: "{{ key_generate_random_pwd }}"
easyrsa_cert_pwd: "{{ key_generate_random_pwd }}"

selfsigned_key: "{{ easyrsa_path_pki }}/private/{{ ga_web_ssl_selfsigned_cn }}.key"
selfsigned_cert: "{{ easyrsa_path_pki }}/issued/{{ ga_web_ssl_selfsigned_cn }}.crt"
selfsigned_fullchain: "{{ easyrsa_path_pki }}/issued/{{ ga_web_ssl_selfsigned_cn }}.fullchain.crt"
selfsigned_ca: "{{ easyrsa_path_pki }}/ca.crt"
