---

- name: UFW | Install package
  apt:
    name: ['ufw']
    state: present

- name: UFW | Reset rules
  community.general.ufw:
    state: reset

- name: UFW | Allow ssh connection
  community.general.ufw:
    rule: 'allow'
    port: "{{ ansible_port | default('22') }}"
    proto: 'tcp'
    comment: 'Ansible managed ssh rule'
  when: ga_ufw_allow_ssh

- name: UFW | Set defaults
  template:
    src: 'templates/etc/default/ufw.j2'
    dest: '/etc/default/ufw'
    owner: 'root'
    group: 'root'
    mode: 0644

- name: UFW | Allow web ports
  community.general.ufw:
    rule: 'allow'
    port: "{{ item }}"
    proto: 'tcp'
    comment: 'Ansible managed ga web port'
  with_items:
    - "{{ ga_web_port_http }}"
    - "{{ ga_web_port_https }}"

- name: UFW | Set logging
  community.general.ufw:
    logging: "{{ ga_ufw_logging }}"

- name: UFW | Enable ufw
  community.general.ufw:
    state: enabled

- name: UFW | Reload
  community.general.ufw:
    state: reloaded
