---

- name: GA | UFW | Install package
  apt:
    name: ['ufw']
    state: present

- name: GA | UFW | Set defaults
  template:
    src: 'templates/etc/default/ufw.j2'
    dest: '/etc/default/ufw'
    owner: 'root'
    group: 'root'
    mode: 0644

- name: GA | UFW | Configuring ssh rule
  import_tasks: ssh.yml
  when: ga_ufw_allow_ssh

- name: GA | UFW | Allowing web ports
  ufw:
    rule: 'allow'
    port: "{{ item.value }}"
    proto: 'tcp'
    comment: 'GrowAutomation {{ item.key }} rule'
  with_items:
    - {'django_http': "{{ ga_web_port_http }}"}
    - {'django_https': "{{ ga_web_port_https }}"}

- name: GA | UFW | Enable ufw
  ufw:
    state: enabled

- name: GA | UFW | Reload
  ufw:
    state: reloaded
