---

- name: 'reload_apache'
  service:
    name: 'apache2.service'
    state: reloaded

- name: 'reload_systemd_deamon'
  systemd:
    daemon_reload: yes

- name: 'enable_certbot'
  service:
    name: 'ga_letsEncryptCertbot.timer'
    enabled: yes
    state: started
