---

# CERTBOT config
#   howto: https://www.digitalocean.com/community/tutorials/how-to-secure-apache-with-let-s-encrypt-on-ubuntu-18-04
#   parameters: https://certbot.eff.org/docs/using.html

letsencrypt_key_size: 4096
letsencrypt_hash_algo: 'sha256'
letsencrypt_dir: '/etc/letsencrypt'

lensencrypt_file_owner: "{{ ga_web_service_user }}"
lensencrypt_file_group: "{{ ga_service_group }}"
lensencrypt_file_mode: 0640

certbot_renew_timer: 'Mon *-*-* 00:00:00'
certbot_force_renewal: false
certbot_verbosity: 'v'

ga_letsencrypt_live_dir: "{{ letsencrypt_dir }}/live/{{ ga_web_key }}"
