---

- name: Installing GrowAutomation
  hosts: all
  become: true
  vars_files:
    - "./vars/main.yml"
  tasks:
    - name: GA Core
      include_role:
        name: core
      when: ga_core_install

    - name: GA Web
      include_role:
        name: web
      when: ga_web_install
