---

- name: Installing GrowAutomation
  hosts: all
  become: true
  vars_files:
    - "./vars/main.yml"
  tasks:
    - name: "Adding info to password file (user {{ ga_sql_user_core }})"
      shell: "echo '{{ ga_sql_user_core }}' >> {{ ga_sql_pwd_random_file }}"
      when: ga_sql_pwd_core == ga_sql_pwd_random_key

    - name: "Generating random password for user {{ ga_sql_user_core }}"
      set_fact:
        ga_sql_pwd_core: "{{ lookup('password', ga_sql_pwd_random_file + ' length=20 chars=ascii_letters,digits,punctuation') }}"
      when: ga_sql_pwd_core == ga_sql_pwd_random_key

    - name: "Adding info to password file (user {{ ga_sql_user_web }})"
      shell: "echo '{{ ga_sql_user_web }}' >> {{ ga_sql_pwd_random_file }}"
      when: ga_sql_pwd_web == ga_sql_pwd_random_key

    - name: "Generating random password for user {{ ga_sql_user_web }}"
      set_fact:
        ga_sql_pwd_web: "{{ lookup('password', ga_sql_pwd_random_file + ' length=20 chars=ascii_letters,digits,punctuation') }}"
      when: ga_sql_pwd_web == ga_sql_pwd_random_key

    - name: Database
      include_role:
        name: db
      when:
        - ga_sql_server == 'localhost'
        - ga_core_install or ga_web_install
        - ga_sql_install

    - name: GA Core
      include_role:
        name: core
      when: ga_core_install

    - name: GA Web
      include_role:
        name: web
      when: ga_web_install
