---

- name: Installing GrowAutomation
  hosts: all
  become: true
  vars_files:
    - "./vars/main.yml"
  tasks:
    - name: Cleaning old password file
      file:
        path: "{{ ga_sql_pwd_random_file }}"
        state: absent

    - name: Generating random password for core
      set_fact:
        ga_sql_pwd_core: "{{ lookup('password', '/dev/null chars=ascii_letters,digits,punctuation length=20') }}"
      no_log: true
      when: ga_sql_pwd_core == ga_sql_pwd_random_key

    - name: Adding password info for core to file
      lineinfile:
        line: "{{ item }}"
        path: "{{ ga_sql_pwd_random_file }}"
        create: yes
        state: present
      no_log: true
      with_items:
        - "{{ ga_sql_user_core }}"
        - "{{ ga_sql_pwd_core }}"

    - name: Generating random password for web
      set_fact:
        ga_sql_pwd_web: "{{ lookup('password', '/dev/null chars=ascii_letters,digits,punctuation length=20') }}"
      no_log: true
      when: ga_sql_pwd_web == ga_sql_pwd_random_key

    - name: Adding password info for web to file
      lineinfile:
        line: "{{ item }}"
        path: "{{ ga_sql_pwd_random_file }}"
        state: present
      no_log: true
      with_items:
        - "{{ ga_sql_user_web }}"
        - "{{ ga_sql_pwd_web }}"

    - name: Database
      import_role:
        name: db
      when:
        - ga_sql_server == 'localhost'
        - ga_core_install or ga_web_install
        - ga_sql_install

    - name: GA Core
      import_role:
        name: core
      when: ga_core_install
